apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Miracle"
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: default/devsecops
    'jenkins.io/job-full-name': 'miracle/miracle'
    dependencytrack/project-id: 8c820c03-522d-4c5c-b56f-8956777fa174
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
