apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Miracle"
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: default/devsecops
    'jenkins.io/job-full-name': 'miracle/miracle'
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
